### ISSUE TITLE
0.3 Release Roadmap

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#225]
#### C++ source

- [x] Density matrix method *(Issue: #39, PR #253, assigned: @chriseclectic)*
- [x] MPS method *(Issue: #56, PR #64, assigned: @merav-aharoni)*
- [x] Measure sampling with readout error *(Issue: #215, assigned: @hhorii )*
- [x] QuantumError to superoperator *(Issue: TODO, PR #253, assigned: @chriseclectic )*
- [x] Circuit optimization passes *(Issue: #285, assigned: @jagunnels )*

#### Python Aer provider

- [ ] Identity scheduler transpiler pass *(Issue: #211, PR #237, assigned: @gadial )*
- [x] 2-qubit error approximation *(Issue: #224, PR #236, assigned: @gadial )*
- [x] Noise insertion transpiler pass *(Issue: #212, PR #239, assigned: @gadial)*
- [x] Special snapshot extensions *(Issue: #300, assigned: @kanejess)*
- [ ] Special gate extensions (multiplexer, multi-controlled) *(Issue: TODO, assigned: TODO)*

### Pulse Simulator
- [ ] Pulse simulator *(Issue: TODO, assigned: @nonhermitian)*

### Postponed

For future release

- GPU statevector method *(Issue: TODO, PR #214, assigned: @doichanj)*
- Pulse noise model and error classes (@nonhermitian)
- Pulse standard error functions (@nonhermitian)

Until interface is decided on

- Distrubted parallel shots and experiments *(Issue: #220, PR #221, assigned: @hitomitak )*
- Unitary Simulator Identity checker method
- Unitary simulator Average gate fidelity method
- Circuit equivalence checker
