### ISSUE TITLE
Add snapshot circuit extensions

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#300]
### What is the expected behavior?

Add circuit extensions for specific snapshot types to make them easier to use. Initially we can start with the currently implemented snapshots and add additional ones in the future. The initial instructions should be:

- [x] `SnapshotProbabilities` #304 : measurement probability snapshot for specified qubits (can apply to all methods of qasm simulator).
- [x] `SnapshotExpectationValue` #305 : exp val snapshots for methods of qasm simulator that support it. Initially this should convert the input to a Pauli expectation value snapshot.
- [x] `SnapshotStatevector` #301 : statevector snapshot for qasm simulator and statevector simulator
- [x] `SnapshotStabilizer` #302 : snapshot for stabilizer method of qasm simulator 
- [x] `SnapshotDensityMatrix` #303 : snapshot for density matrix method of qasm simulator (could be added to other methods in future)
- [x] Add snapshot tests
- [ ] Make snapshot tutorial notebook for qiskit-tutorials

I will create separate issues for each snapshot type with more details and collect them here. 

There already exists a general `Snapshot` instruction in Terra, this can be used as the super class for these extensions. This base Snapshot instruction should probably be copied/moved to Aer for now.

 *Note: There is an issue with parameters and validation that they must be wrapped in numpy or sympy to validate*.

**Comment by chriseclectic** [comment]
@kanejess will get started on this

**Comment by atilag** [comment]
@chriseclectic I think we can close this issue, right?
