### ISSUE TITLE
Aer 0.4 Release Tasks

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#515]
### Main Features

- [x] GPU support in QasmSimulator (#511 @doichanj @atilag )
- [x] Migrate QasmSimulator from Cython to Pybind (@ereastman @atilag)
- [x] Pulse Simulator backend (@DanPuzzuoli)
- ~Approximate simulation in MPS method~  (@merav-aharoni)

#### Qasm Simulator

- [x] Test wheel build and distribution (@atilag @mtreinish )

- Fix sdist builds and add testing: https://github.com/Qiskit/qiskit-aer/pull/560

- [x] GPU Qasm statevector method (#511, @doichanj )
- [x] Pybind wrappers for Result objects (#504, @ereastman )
- ~MPS expectation values~ (#509, @yaelbh )
- ~MPS bond-dimension truncation~ (#475 @merav-aharoni )

#### Pulse Simulator

- [x] Transmon system generation functions (#514 @DanPuzzuoli )
-  ~Debug ZVODE errors~ (#499 @DanPuzzuoli )
- [x] Finish API documentation (#433 @DanPuzzuoli)
- [x] Cleanup default behaviour, kwargs etc (#500, #501)
- [x] Add additional unittests and integration tests (@DanPuzzuoli haggai)

#### Bugs

- [x] Remove Initialize from unitary simulator basis gates (#497 )
- [x] Add cvxpy requirement to setup.py (#490) 
- [x] Close or update old build related issues (#17, #18, #203, #233, #242, #392 @atilag )

*NB: dashed items are postponed till after release*
